{{- define "imagePullSecret" }}
{{- with .Values.regcred }}
{{- printf "{\"auths\":{\"ghcr.io\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"a@a.com\",\"auth\":\"%s\"}}}" .user .key (printf "%s:%s" .user .key | b64enc) | b64enc }}
{{- end }}
{{- end }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.regcred.name }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
