{{ if .Values.staticData.install }}
kind: Job
apiVersion: batch/v1
metadata:
  name: sql-create-personel-static-data
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-90"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: initial-creator
          image: {{ .Values.staticData.image}}
          env:
            - name: SQLADDRESS
              value: "{{ .Values.sql.connection.server }},{{ .Values.sql.connection.port }}"
            - name: SQLUSER
              value: "{{ .Values.sql.connection.user }}"
            - name: SQLPASS
              value: "{{ .Values.sql.connection.password }}"
            - name: DBNAME
              value: "{{ .Values.dbNames.PERSONEL }}"
{{ end }}
