{{ if .Values.longhorn }}
{{ if .Values.longhorn.install }}
{{- $longhornSC := (lookup "storage.k8s.io/v1" "StorageClass" "" "longhorn") -}}
{{- if not $longhornSC }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  fsType: "ext4"
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  dataLocality: "best-effort"
{{- else if eq $longhornSC.provisioner "driver.longhorn.io"}}
{{ $longhornSC | mustToPrettyJson }}
{{- else}}
{{- fail "the existing longhorn storageclass doesn't have provisioner as driver.longhorn.io" }}
{{- end}}
{{- end }}
{{- end }}
