{{ if .Values.longhorn }}
{{ if .Values.longhorn.install }}
apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-uninstall
  namespace: longhorn-system
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 1
  template:
    metadata:
      name: longhorn-uninstall
    spec:
      containers:
        - name: longhorn-uninstall
          image: longhornio/longhorn-manager:v1.2.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - longhorn-manager
            - uninstall
            - --force
          env:
            - name: LONGHORN_NAMESPACE
              value: longhorn-system
      restartPolicy: OnFailure
      serviceAccountName: longhorn-service-account
{{ end }}
{{ end }}
