# Programlarımıza erişim için gerekli GitHub erişim anahtarı
regcred:
  enabled: true
  user: talyabilisim
  key: REQUIRED-github-access-token
# NodeJS Web Servis
worker:
  host: nodejs4001
  image: ghcr.io/travelaps/nodejs-worker:v455
  replicas: 1
# SQL Server
sql:
  install: true
  pid: Standard
  saPassword: aA!01012000
  memoryLimit: 16000
  tcpPort: 1433
  agentEnabled: true
  runCreationScripts: true
  elektraAdminUser:
    username: elektraweb
    password: eE!01012000
  volumes:
    - name: mssql-data
      hostPath:
        path: /elektraweb/sql-data
        type: DirectoryOrCreate
  volumeMounts:
    - name: mssql-data
      mountPath: /var/opt/mssql/data
#  persistentVolumeClaims:
#    mssql-data:
#      accessModes:
#        - ReadWriteMany
#      storageClassName: longhorn
#      resources:
#        requests:
#          storage: 50Gi
# Angus
angus:
  install: true
  image: ghcr.io/travelaps/angus:v240
  host: elektraweb
  displayName: ElektraWeb
  shortName: ewebcloud
  logo: elektraweb.png
# Pos
pos:
  install: true
  image: ghcr.io/travelaps/pos-ng11:v84
  host: elektrawebpos
# .NET Core FRX Rapor Programı
reporting:
  install: true
  host: elektrawebreport
# Kanal Yönetimi
channelManager:
  install: false
# Kubernetes Dashboard
dashboard:
  install: false
  namespace: kube-system
  createNamespace: false
# Kubernetes Dashboard'a dışarıdan erişim için ingress/user
dashboardAccess:
  ingress:
    enabled: false
    host: kubernetes.docker.internal
  adminUser:
    enabled: false
    name: admin-user
# Nginx Ingress
ingressNginx:
  install: false
  class: public
  namespace: ingress
  createNamespace: true
#Create Hotel?
hotel:
  install: false
  #Mutlaka once cloudda register olup kendi HOTELID'nizi yazmalısınız
  hotelid: 24434
  hotelname: localtesthotel
#STATIC DATA
staticData:
  install: true
longhorn:
  install: false
  # microk8s ise rootDir alttaki gibi, managed ortamlarda bu zaten ayarlı olduğundan boş olmalı
  rootDir: # /var/snap/microk8s/common/var/lib/kubelet


