regcred:
  user: talyabilisim
  key: GITHUB_TOKEN
angus:
  image: ghcr.io/travelaps/angus:tt-v2
  host: KOKPIT_URL
  azureSettings:
    container: files
    storageUrl: NODEJS_HTTP_URL
    token: "?token=TOKEN&se=EXPIRATION_TIME"
http:
  image: ghcr.io/travelaps/nodejs-http:v28-beta
  host: NODEJS_HTTP_URL
worker:
  image: ghcr.io/travelaps/nodejs-worker:tt-v1
  config:
    dbConfig:
      user: DB_USER
      password: DB_PASSWORD
      server: DB_ADDR
      trustServerCertificate: true
portal:
  image: ghcr.io/travelaps/portal:v112-tt
  host: PORTAL_HTTP_URL
fileUploader:
  image: ghcr.io/travelaps/reportingfull:latest
  host: NODEJS_HTTP_URL
  env:
    ALLOWED_TOKENS: '["TOKEN"]'
ingressNginx:
  install: true
  class: public
  namespace: ingress
  createNamespace: true
